import 'package:hive/hive.dart';

part 'game.g.dart'; // This file will be generated by the build_runner

@HiveType(typeId: 0) // Unique ID for this type.
class Game extends HiveObject {
  @HiveField(0)
  String title;

  @HiveField(1)
  String platform;

  @HiveField(2)
  String genre;

  @HiveField(3)
  String status; // e.g., "Now Playing", "Beaten"

  @HiveField(4)
  DateTime dateAdded;

  // Add other fields from your design here later, e.g., developer, priority.
  // Let's keep it simple for now.

  Game({
    required this.title,
    required this.platform,
    required this.genre,
    required this.status,
    required this.dateAdded,
  });
}