import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart'; // Import hive_flutter
import 'package:gamelog/models/game.dart';       // Import our Game model

void main() async { // main function now needs to be async
  // Ensure that Flutter's binding is initialized before calling any Flutter specific code.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive for Flutter. This sets up a directory on the device to store the database.
  await Hive.initFlutter();

  // Register the adapter for our Game class. This adapter was auto-generated by build_runner
  // and tells Hive how to serialize and deserialize the Game object.
  // Without this, Hive wouldn't know how to save your custom object.
  Hive.registerAdapter(GameAdapter());

  // Open a box named 'games'. A box is like a table in a SQL database or a
  // collection in a NoSQL database. We are specifying that this box will store
  // objects of type Game.
  await Hive.openBox<Game>('games');

  // Once Hive is set up, run the app.
  runApp(const GameLogApp());
}

class GameLogApp extends StatelessWidget {
  const GameLogApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GameLog',
      // We are defining a custom dark theme that matches the aesthetic of the inspiration image.
      theme: ThemeData.dark().copyWith(
        primaryColor: const Color(0xFF8A2BE2), // Example: BlueViolet, not heavily used but good to set.
        scaffoldBackgroundColor: const Color(0xFF1A1A1A), // A very dark grey for the main background
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF222222), // Slightly lighter grey for the app bar
          elevation: 0, // No shadow for a flatter look
        ),
        floatingActionButtonTheme: FloatingActionButtonThemeData(
          backgroundColor: const Color(0xFF9D4EDD), // The primary purple color for the FAB
        ),
        // The color scheme defines the set of colors for the app's components.
        colorScheme: const ColorScheme.dark().copyWith(
          primary: const Color(0xFF9D4EDD), // A nice purple for buttons, highlights
          secondary: const Color(0xFFC77DFF), // A lighter purple for accents
          onPrimary: Colors.white, // Text color on top of primary color (e.g., on buttons)
          surface: const Color(0xFF2C2C2C), // Color for card backgrounds
        ),
      ),
      debugShowCheckedModeBanner: false, // Hides the "debug" banner in the top right
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('My GameLog'),
      ),
      body: const Center(
        child: Text('Welcome to your Backlog!'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          // In the next phases, this button will open a new screen to add a game.
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}